### ISSUE TITLE
Setuptools import error with uproot4

### ISSUE THREAD

**Issue by Dominic-Stafford** [scikit-hep/uproot5#1259]
When attempting to call the `uproot.extras.awkward()` function from uproot 4.3.7 with an up-to-date version of setuptools (>=71) I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/dust/cms/user/stafford/tmp/uproot_tests/lib/python3.9/site-packages/uproot/extras.py", line 36, in awkward
    if parse_version("1") < parse_version(awkward.__version__) < parse_version("2"):
  File "/nfs/dust/cms/user/stafford/tmp/uproot_tests/lib/python3.9/site-packages/uproot/_util.py", line 99, in parse_version
    return setuptools.extern.packaging.version.parse(version)
AttributeError: module 'setuptools' has no attribute 'extern'
```

It seems the `setuptools.extern` module has been dropped. I don't get this error with uproot 5.3.10, however we're currently running a medium-sized framework based on coffea 0.7, and haven't managed to make the jump to coffea 2024/dask awkward. Would it be possible to have a new uproot 4.3 release fixing this bug, please?

**Comment by namzloh** [comment]
I asked Jim P over slack about pinning `setuptools<71` for a new uproot release. He indicated that it would be significant work to deploy a new release for this and asked if coffea users could just pin it themselves.

**Comment by holzman** [comment]
I asked Jim P over slack about pinning setuptools<71 for a new uproot release. He indicated that it would be significant work to deploy a new release for this and asked if coffea users could just pin it themselves.

**Comment by jpivarski** [comment]
I'm going to leave this open so that others with the same problem can find it. If self-pinning is a _significant_ issue, then I'll see about making a new Uproot 4.x release.
