### ISSUE TITLE
uproot.concatenate craches with 'cut' and 'library="pd"'

### ISSUE THREAD

**Issue by apoluekt** [scikit-hep/uproot5#1321]
Hi, 

uproot 5.4.1 crashes when I try to read the tuple supplying the 'cut' argument with library='pd': 

```
bash-5.1$ python 
Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> uproot.__version__
'5.4.1'
>>> uproot.concatenate("filtered.root", library="pd", cut="run>0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/pidgen/2024-10-15_18-48/linux-64/lib/python3.12/site-packages/uproot/behaviors/TBranch.py", line 374, in concatenate
    arrays = library.global_index(arrays, global_start)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/lhcbdev.cern.ch/conda/envs/pidgen/2024-10-15_18-48/linux-64/lib/python3.12/site-packages/uproot/interpretation/library.py", line 922, in global_index
    index = arrays.index.arrays
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Index' object has no attribute 'arrays'. Did you mean: 'array'?
```

Thanks in advance!

**Comment by jpivarski** [comment]
PR #1322 should fix it.
