### ISSUE TITLE
`AttributeError` when calling `arrays()` on a branch holding objects with custom streamer

### ISSUE THREAD

**Issue by gipert** [scikit-hep/uproot5#607]
```pycon
>>> import uproot
>>> uproot.__version__
'4.2.2'
```

I'm trying to read objects with custom ROOT streamer collected in a TTree in [this file here](https://github.com/legend-exp/legend-testdata/blob/main/data/mgdo/gerda-run0050-20150826T170402Z-cal-ged-tier1.root). This is what I tried so far:
```pycon
>>> import uproot
>>> events = uproot.open("gerda-run0050-20150826T170402Z-cal-ged-tier1.root:MGTree")
>>> events.show()
name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
event                | MGTEvent                 | AsObjects(AsDynamic(model=M...
>>> events["event"].interpretation
AsObjects(AsDynamic(model=Model_MGTEvent))
>>> events["event"].arrays()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 1059, in arrays
    return self.parent.arrays(
  File "/usr/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 1125, in arrays
    _ranges_or_baskets_to_arrays(
  File "/usr/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 3502, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/usr/lib/python3.10/site-packages/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/usr/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 3446, in basket_to_array
    basket_arrays[basket.basket_num] = interpretation.basket_array(
  File "/usr/lib/python3.10/site-packages/uproot/interpretation/objects.py", line 140, in basket_array
    form = self.awkward_form(branch.file, index_format="i64")
  File "/usr/lib/python3.10/site-packages/uproot/interpretation/objects.py", line 120, in awkward_form
    return self._model.awkward_form(
  File "/usr/lib/python3.10/site-packages/uproot/containers.py", line 304, in awkward_form
    parameters={"uproot": {"as": "array", "header": self._header}},
AttributeError: 'AsDynamic' object has no attribute '_header'. Did you mean: 'header'?
```
Is this something expected or is it a bug? Where do I need to start to be able to decode this? Here's some (hopefully useful) information:
```pycon
>>> import ROOT
>>> f = ROOT.TFile("gerda-run0050-20150826T170402Z-cal-ged-tier1.root")
>>> f.GetVersion()
60410
>>> f.ShowStreamerInfo()
OBJ: TList	TList	Doubly linked list : 0

StreamerInfo for class: TNamed, version=1, checksum=0xdfb74a3c
  TObject        BASE            offset=  0 type=66 Basic ROOT object   
  TString        fName           offset=  0 type=65 object identifier   
  TString        fTitle          offset=  0 type=65 object title        

StreamerInfo for class: TObject, version=1, checksum=0x901bc02d
  unsigned int   fUniqueID       offset=  0 type=13 object unique identifier
  unsigned int   fBits           offset=  0 type=15 bit field status word

StreamerInfo for class: TList, version=5, checksum=0x69c5c3bb
  TSeqCollection BASE            offset=  0 type= 0 Sequenceable collection ABC

StreamerInfo for class: TSeqCollection, version=0, checksum=0xfc6c3bc6
  TCollection    BASE            offset=  0 type= 0 Collection abstract base class

StreamerInfo for class: TCollection, version=3, checksum=0x57e3cb9c
  TObject        BASE            offset=  0 type=66 Basic ROOT object   
  TString        fName           offset=  0 type=65 name of the collection
  int            fSize           offset=  0 type= 3 number of elements in collection

StreamerInfo for class: MGTEvent, version=9, checksum=0xed4b3be7
  MGTDataObject  BASE            offset=  0 type= 0 MJ Data Object base class
  MGVMemoryCheckable BASE            offset=  0 type= 0                     
  MGEventType::EventType fEventType      offset=  0 type= 3 flag to identify e.g. events from pulser
  double         fETotal         offset=  0 type= 8 sum of energies of Ge detector hit in this event
  double         fTime           offset=  0 type= 8 time of the first Ge detector hit (since run start)
  TClonesArray*  fWaveforms      offset=  0 type=64 TClonesArray of waveforms
  TClonesArray*  fDigitizerData  offset=  0 type=64 TClonesArray of digitizer data
  vector<bool>*  fActiveID       offset=  0 type=71 ,stl=41, ctype=21, Map of active IDs in the event
  bool           fUseAuxWaveformArray offset=  0 type=18 flag to use or ignore auxiliary waveform array
  TClonesArray*  fAuxWaveforms   offset=  0 type=64 Additional high frequency traces
  int            fEventNumber    offset=  0 type= 3 Unique number pointing to event in file

StreamerInfo for class: MGTDataObject, version=2, checksum=0xd3e7dd50
  TNamed         BASE            offset=  0 type=67 The basis for a named object (name, title)

StreamerInfo for class: MGVMemoryCheckable, version=1, checksum=0x752eeea5

StreamerInfo for class: TString, version=2, checksum=0x17419

StreamerInfo for class: TClonesArray, version=4, checksum=0xb6c0ca63
  TObjArray      BASE            offset=  0 type= 0 An array of objects 

StreamerInfo for class: TObjArray, version=3, checksum=0xa99e6552
  TSeqCollection BASE            offset=  0 type= 0 Sequenceable collection ABC
  int            fLowerBound     offset=  0 type= 3 Lower bound of the array
  int            fLast           offset=  0 type= 3 Last element in array containing an object

StreamerInfo for class: TParameter<int>, version=2, checksum=0xfe8557f8
  TObject        BASE            offset=  0 type=66 Basic ROOT object   
  TString        fName           offset=  0 type=65                     
  int            fVal            offset=  0 type= 3                     

StreamerInfo for class: MGTWaveform, version=5, checksum=0xf5508ea6
  MGTDataObject  BASE            offset=  0 type= 0 MJ Data Object base class
  MGWaveform     BASE            offset=  0 type= 0                     
  MGVMemoryCheckable BASE            offset=  0 type= 0                     
  TF1*           fWaveformFunction offset=  0 type=64                     
  MGTWaveform::EWFEncScheme fWFEncScheme    offset=  0 type= 3                     

StreamerInfo for class: MGWaveform, version=1, checksum=0x9b7a3848
  double         fSampFreq       offset=  0 type= 8 sampling frequency  
  double         fTOffset        offset=  0 type= 8 global time of sample 0
  MGWaveform::EWFType fWFType         offset=  0 type= 3 waveform type       
  vector<double> fData           offset=  0 type=300 ,stl=1, ctype=8, internal data array holding sample values
  int            fID             offset=  0 type= 3 ID for storing, e.g., which detector / contact this wf comes from

StreamerInfo for class: TF1, version=9, checksum=0x69241a7c
  TNamed         BASE            offset=  0 type=67 The basis for a named object (name, title)
  TAttLine       BASE            offset=  0 type= 0 Line attributes     
  TAttFill       BASE            offset=  0 type= 0 Fill area attributes
  TAttMarker     BASE            offset=  0 type= 0 Marker attributes   
  double         fXmin           offset=  0 type= 8 Lower bounds for the range
  double         fXmax           offset=  0 type= 8 Upper bounds for the range
  int            fNpar           offset=  0 type= 3 Number of parameters
  int            fNdim           offset=  0 type= 3 Function dimension  
  int            fNpx            offset=  0 type= 3 Number of points used for the graphical representation
  int            fType           offset=  0 type= 3 (=0 for standard functions, 1 if pointer to function)
  int            fNpfits         offset=  0 type= 3 Number of points used in the fit
  int            fNDF            offset=  0 type= 3 Number of degrees of freedom in the fit
  double         fChisquare      offset=  0 type= 8 Function fit chisquare
  double         fMinimum        offset=  0 type= 8 Minimum value for plotting
  double         fMaximum        offset=  0 type= 8 Maximum value for plotting
  vector<double> fParErrors      offset=  0 type=300 ,stl=1, ctype=8, Array of errors of the fNpar parameters
  vector<double> fParMin         offset=  0 type=300 ,stl=1, ctype=8, Array of lower limits of the fNpar parameters
  vector<double> fParMax         offset=  0 type=300 ,stl=1, ctype=8, Array of upper limits of the fNpar parameters
  vector<double> fSave           offset=  0 type=300 ,stl=1, ctype=8, Array of fNsave function values
  bool           fNormalized     offset=  0 type=18 Normalization option (false by default)
  double         fNormIntegral   offset=  0 type= 8 Integral of the function before being normalized
  TFormula*      fFormula        offset=  0 type=64 Pointer to TFormula in case when user define formula
  TF1Parameters* fParams         offset=  0 type=69 Pointer to Function parameters object (exusts only for not-formula functions)

StreamerInfo for class: TAttLine, version=2, checksum=0x94074549
  short          fLineColor      offset=  0 type= 2 line color          
  short          fLineStyle      offset=  0 type= 2 line style          
  short          fLineWidth      offset=  0 type= 2 line width          

StreamerInfo for class: TAttFill, version=2, checksum=0xffd92a92
  short          fFillColor      offset=  0 type= 2 fill area color     
  short          fFillStyle      offset=  0 type= 2 fill area style     

StreamerInfo for class: TAttMarker, version=2, checksum=0x291d8bec
  short          fMarkerColor    offset=  0 type= 2 Marker color index  
  short          fMarkerStyle    offset=  0 type= 2 Marker style        
  float          fMarkerSize     offset=  0 type= 5 Marker size         

StreamerInfo for class: TFormula, version=10, checksum=0x9cab775b
  TNamed         BASE            offset=  0 type=67 The basis for a named object (name, title)
  vector<double> fClingParameters offset=  0 type=300 ,stl=1, ctype=8, parameter values    
  bool           fAllParametersSetted offset=  0 type=18 flag to control if all parameters are setted
  map<TString,int,TFormulaParamOrder> fParams         offset=  0 type=300  (nodelete) ,stl=4, ctype=61, list of  parameter names
  TString        fFormula        offset=  0 type=65                     
  vector<TObject*> fLinearParts    offset=  0 type=300  (nodelete) ,stl=1, ctype=63, vector of linear functions

StreamerInfo for class: TF1Parameters, version=1, checksum=0xd703028e
  vector<double> fParameters     offset=  0 type=300 ,stl=1, ctype=8, parameter values    
  vector<string> fParNames       offset=  0 type=300 ,stl=1, ctype=61, parameter names     

StreamerInfo for class: GETGERDADigitizerData, version=1, checksum=0xa48d9d0a
  GETVGERDADigitizerData BASE            offset=  0 type= 0                     

StreamerInfo for class: GETVGERDADigitizerData, version=2, checksum=0xcfc9fbe8
  MGTVDigitizerData BASE            offset=  0 type= 0 DigitizerData class 
  double         fClockFrequency offset=  0 type= 8                     
  int            fEventNumber    offset=  0 type= 3                     
  unsigned long  fPretrigger     offset=  0 type=14                     
  unsigned long  fTriggerNumber  offset=  0 type=14                     
  unsigned int   fDecimalTimeStamp offset=  0 type=13                     
  bool           fIsMuVetoed     offset=  0 type=18                     
  unsigned int   fMuVetoSample   offset=  0 type=13                     
  bool           fIsInverted     offset=  0 type=18                     
  MGWaveformTag::EWaveformTag fWaveformTag    offset=  0 type= 3                     

StreamerInfo for class: MGTVDigitizerData, version=1, checksum=0x1c64498c
  MGTDataObject  BASE            offset=  0 type= 0 MJ Data Object base class
  MGVDigitizerData BASE            offset=  0 type= 0                     

StreamerInfo for class: MGVDigitizerData, version=1, checksum=0x640c47e7
  double         fEnergy         offset=  0 type= 8                     
  unsigned long  fTimeStamp      offset=  0 type=14                     
  unsigned int   fID             offset=  0 type=13                     
  unsigned long  fIndex          offset=  0 type=14                     

StreamerInfo for class: TTree, version=19, checksum=0x58a396eb
  TNamed         BASE            offset=  0 type=67 The basis for a named object (name, title)
  TAttLine       BASE            offset=  0 type= 0 Line attributes     
  TAttFill       BASE            offset=  0 type= 0 Fill area attributes
  TAttMarker     BASE            offset=  0 type= 0 Marker attributes   
  Long64_t       fEntries        offset=  0 type=16 Number of entries   
  Long64_t       fTotBytes       offset=  0 type=16 Total number of bytes in all branches before compression
  Long64_t       fZipBytes       offset=  0 type=16 Total number of bytes in all branches after compression
  Long64_t       fSavedBytes     offset=  0 type=16 Number of autosaved bytes
  Long64_t       fFlushedBytes   offset=  0 type=16 Number of autoflushed bytes
  double         fWeight         offset=  0 type= 8 Tree weight (see TTree::SetWeight)
  int            fTimerInterval  offset=  0 type= 3 Timer interval in milliseconds
  int            fScanField      offset=  0 type= 3 Number of runs before prompting in Scan
  int            fUpdate         offset=  0 type= 3 Update frequency for EntryLoop
  int            fDefaultEntryOffsetLen offset=  0 type= 3 Initial Length of fEntryOffset table in the basket buffers
  int            fNClusterRange  offset=  0 type= 6 Number of Cluster range in addition to the one defined by 'AutoFlush'
  Long64_t       fMaxEntries     offset=  0 type=16 Maximum number of entries in case of circular buffers
  Long64_t       fMaxEntryLoop   offset=  0 type=16 Maximum number of entries to process
  Long64_t       fMaxVirtualSize offset=  0 type=16 Maximum total size of buffers kept in memory
  Long64_t       fAutoSave       offset=  0 type=16 Autosave tree when fAutoSave entries written or -fAutoSave (compressed) bytes produced
  Long64_t       fAutoFlush      offset=  0 type=16 Autoflush tree when fAutoFlush entries written or -fAutoFlush (compressed) bytes produced
  Long64_t       fEstimate       offset=  0 type=16 Number of entries to estimate histogram limits
  Long64_t*      fClusterRangeEnd offset=  0 type=56 [fNClusterRange] Last entry of a cluster range.
  Long64_t*      fClusterSize    offset=  0 type=56 [fNClusterRange] Number of entries in each cluster for a given range.
  TObjArray      fBranches       offset=  0 type=61 List of Branches    
  TObjArray      fLeaves         offset=  0 type=61 Direct pointers to individual branch leaves
  TList*         fAliases        offset=  0 type=64 List of aliases for expressions based on the tree branches.
  TArrayD        fIndexValues    offset=  0 type=62 Sorted index values 
  TArrayI        fIndex          offset=  0 type=62 Index of sorted values
  TVirtualIndex* fTreeIndex      offset=  0 type=64 Pointer to the tree Index (if any)
  TList*         fFriends        offset=  0 type=64 pointer to list of friend elements
  TList*         fUserInfo       offset=  0 type=64 pointer to a list of user objects associated to this Tree
  TBranchRef*    fBranchRef      offset=  0 type=64 Branch supporting the TRefTable (if any)

StreamerInfo for class: TBranchObject, version=1, checksum=0x7706da6d
  TBranch        BASE            offset=  0 type= 0 Branch descriptor   
  TString        fClassName      offset=  0 type=65 Class name of referenced object

StreamerInfo for class: TBranch, version=12, checksum=0x59108cb8
  TNamed         BASE            offset=  0 type=67 The basis for a named object (name, title)
  TAttFill       BASE            offset=  0 type= 0 Fill area attributes
  int            fCompress       offset=  0 type= 3 Compression level and algorithm
  int            fBasketSize     offset=  0 type= 3 Initial Size of  Basket Buffer
  int            fEntryOffsetLen offset=  0 type= 3 Initial Length of fEntryOffset table in the basket buffers
  int            fWriteBasket    offset=  0 type= 3 Last basket number written
  Long64_t       fEntryNumber    offset=  0 type=16 Current entry number (last one filled in this branch)
  int            fOffset         offset=  0 type= 3 Offset of this branch
  int            fMaxBaskets     offset=  0 type= 6 Maximum number of Baskets so far
  int            fSplitLevel     offset=  0 type= 3 Branch split level  
  Long64_t       fEntries        offset=  0 type=16 Number of entries   
  Long64_t       fFirstEntry     offset=  0 type=16 Number of the first entry in this branch
  Long64_t       fTotBytes       offset=  0 type=16 Total number of bytes in all leaves before compression
  Long64_t       fZipBytes       offset=  0 type=16 Total number of bytes in all leaves after compression
  TObjArray      fBranches       offset=  0 type=61 -> List of Branches of this branch
  TObjArray      fLeaves         offset=  0 type=61 -> List of leaves of this branch
  TObjArray      fBaskets        offset=  0 type=61 -> List of baskets of this branch
  int*           fBasketBytes    offset=  0 type=43 [fMaxBaskets] Length of baskets on file
  Long64_t*      fBasketEntry    offset=  0 type=56 [fMaxBaskets] Table of first entry in each basket
  Long64_t*      fBasketSeek     offset=  0 type=56 [fMaxBaskets] Addresses of baskets on file
  TString        fFileName       offset=  0 type=65 Name of file where buffers are stored ("" if in same file as Tree header)

StreamerInfo for class: TLeafObject, version=4, checksum=0x26ba7c4c
  TLeaf          BASE            offset=  0 type= 0 Leaf: description of a Branch data type
  bool           fVirtual        offset=  0 type=18 Support for polymorphism, when set classname is written with object.

StreamerInfo for class: TLeaf, version=2, checksum=0x6d1e8152
  TNamed         BASE            offset=  0 type=67 The basis for a named object (name, title)
  int            fLen            offset=  0 type= 3 Number of fixed length elements
  int            fLenType        offset=  0 type= 3 Number of bytes for this data type
  int            fOffset         offset=  0 type= 3 Offset in ClonesArray object (if one)
  bool           fIsRange        offset=  0 type=18 (=kTRUE if leaf has a range, kFALSE otherwise)
  bool           fIsUnsigned     offset=  0 type=18 (=kTRUE if unsigned, kFALSE otherwise)
  TLeaf*         fLeafCount      offset=  0 type=64 Pointer to Leaf count if variable length (we do not own the counter)

StreamerInfo for class: TBranchRef, version=1, checksum=0x8a9bd841
  TBranch        BASE            offset=  0 type= 0 Branch descriptor   
  TRefTable*     fRefTable       offset=  0 type=64 pointer to the TRefTable

StreamerInfo for class: TRefTable, version=3, checksum=0x8c895b85
  TObject        BASE            offset=  0 type=66 Basic ROOT object   
  int            fSize           offset=  0 type= 3 dummy for backward compatibility
  TObjArray*     fParents        offset=  0 type=64 array of Parent objects  (eg TTree branch) holding the referenced objects
  TObject*       fOwner          offset=  0 type=64 Object owning this TRefTable
  vector<string> fProcessGUIDs   offset=  0 type=300 ,stl=1, ctype=61, UUIDs of TProcessIDs used in fParentIDs
 OBJ: TList	listOfRules	Doubly linked list : 0
  OBJ: TObjString	type=read sourceClass="TTree" targetClass="TTree" version="[-16]" source="" target="fDefaultEntryOffsetLen" code="{ fDefaultEntryOffsetLen = 1000; }" 	Collectable string class : 0 at: 0x3e81670
  OBJ: TObjString	type=read sourceClass="TTree" targetClass="TTree" version="[-18]" source="" target="fNClusterRange" code="{ fNClusterRange = 0; }" 	Collectable string class : 0 at: 0x3e98cc0
  ```

**Comment by gipert** [comment]
Update: If I use another library (e.g. `'np'`), I get a different error message:
```pycon
>>> f['MGTree']['event'].array(library="np")
[...]
attempting to get bytes 3221179793:3221179799
outside expected range 0:11791 for this Chunk
in file gerda-run0100-20190104T135505Z-cal-ged-tier1.root
in object /MGTree;1
```

**Comment by jpivarski** [comment]
See the comment in #674: although I've fixed the exact issue you reported (thanks!), I don't think we're going to be solve all of the issues in such a complex data type (sorry).

At least the error message is better—it says there's an issue in deserialization, which there is.

**Comment by gipert** [comment]
I understand, thanks a lot for letting me know! Do you have a recommendation on how to proceed? I really need to decode those files into Python data types.

**Comment by jpivarski** [comment]
Okay, I looked into it (spent a few hours on it) and there's just too much advanced ROOT I/O in this data type to figure out.

Generally, the hardest part is determining whether objects have headers or not and how big those headers are, and the first issue is that kind of issue: one of MGTEvent's base classes moves the file pointer 2 bytes too far. Arbitrarily moving that back, I can see that the first event's `fEventType` is `0`, `fETotal` is `86.98358966676925`, and `fTime` is `1440608785.364249` (August 26, 2015).

But then past that, `fWaveforms` and `fDigitizerData` had to be skipped for a reason I didn't investigate and we hit `fActiveID`, an `std::vector<bool>` written with memberwise serialization. Memberwise serialization is a long-standing unimplemented case in Uproot (#38). It's a second I/O system within ROOT I/O that we just haven't had the time to reverse engineer. (There are no specifications at this level of detail.)

Can this file be rewritten with `splitLevel=99`, to try to get each field into its own TBranch? That makes things a lot easier (and faster[^1]), and even if there are still some TBranches that can't be interpreted, they might not be the ones you need.

Also if you can rewrite the file, manually converting it into simpler data types (analogous to NanoAOD) would also make things a lot easier (and faster[^1]). In essence, this is avoiding the more advanced features of ROOT I/O.

[^1]: Faster: as a single TBranch, the serialization format is complex and we're forced to iterate over the fields of each struct, one by one. When split into multiple TBranches, some of them have homogeneous type (e.g. a big block of integers with nothing in between). We don't need to iterate over data of homogeneous type; we can just cast it as a NumPy array, which takes the same (small) amount of time independently of how large the array is.

**Comment by gipert** [comment]
Hi Jim, thanks a lot for looking into it! Unfortunately, there's years and years of data in ROOT format that I'd like to be able to decode on-the-fly (and, in my specific case, re-encode in HDF5). Rewriting it or converting it to some other intermediate format would be complicated.

At this point, I'd rather implement some decoder for the original DAQ files.

Thanks a lot again!
