### ISSUE TITLE
Problem writing TList of TObjString

### ISSUE THREAD

**Issue by lobis** [scikit-hep/uproot5#762]
I have noticed a problem when trying to write a `TList` of `TObjString` objects.

**I woud like to reproduce the following file created by root**:

```c++
const std::vector<const char*> strings = {"this", "is", "a", "test"};

auto f = TFile::Open("list.root", "RECREATE");

auto l = new TList();

for (const auto& s: strings) {
    l->Add(new TObjString(s));
}

l->Write("listOfStrings", TObject::kSingleKey); // if TObject::kSingleKey is not specified, each item on the list is written as a key to the root file

f->Close();
```

<details>
  <summary>Opening the file with root:</summary>

```
root@2a578f2dc0f6:~# root list.root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.26/06                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Sep 25 2022, 12:37:00                 |
  | From tags/v6-26-06@v6-26-06                                      |
  | With c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0                        |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------

root [0]
Attaching file list.root as _file0...
(TFile *) 0x5572bae81430
root [1] .ls
TFile**         list.root
 TFile*         list.root
  KEY: TList    listOfStrings;1 Doubly linked list
root [2] listOfStrings->Print(nullptr)
Collection name='TList', class='TList', size=4
 TObjString = this
 TObjString = is
 TObjString = a
 TObjString = test
root [3]
```
</details>

My attempt to do this using `uproot` makes use of the `uproot.writing.identify.to_TList` method which according to its description should be able to write a `TList` of root objects into a root file.

Python to write `TList` into file:

```python
import uproot
print(f"{uproot.__version__=}")

strings = ["this", "is", "a", "test"]

listOfStrings = uproot.writing.identify.to_TList([uproot.writing.identify.to_TObjString(s) for s in strings])
# listOfStrings = uproot.writing.identify.to_TList([]) # this works

print(f"{listOfStrings=}")

filename = "list.root"
key = "listOfStrings"

with uproot.recreate(filename) as f:
    f[key] = listOfStrings
```

```
uproot.__version__='5.0.0rc4'
listOfStrings=<TList of 4 items at 0x7f3b987d8eb0>
```

<details>
  <summary>Reading the file with root does not work:</summary>

```
root@2a578f2dc0f6:~# root list.root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.26/06                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Sep 25 2022, 12:37:00                 |
  | From tags/v6-26-06@v6-26-06                                      |
  | With c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0                        |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------

root [0]
Attaching file list.root as _file0...
(TFile *) 0x557bde1ff7a0
root [1] .ls
TFile**         list.root
 TFile*         list.root
  KEY: TList    listOfStrings;1
root [2] listOfStrings
Error in <TExMap::Remove>: key 90432 not found at 396
Warning in <TBufferFile::CheckObject>: reference to object of unavailable class TObject, offset=90432 pointer will be 0
Error in <TExMap::Remove>: key 2424831 not found at 371
Warning in <TBufferFile::CheckObject>: reference to object of unavailable class TObject, offset=2424831 pointer will be 0
Error in <TRint::HandleTermInput()>: std::length_error caught: basic_string::_M_replace_aux
root [3] listOfStrings->Print(nullptr)
Error in <TExMap::Remove>: key 90432 not found at 396
Warning in <TBufferFile::CheckObject>: reference to object of unavailable class TObject, offset=90432 pointer will be 0
Error in <TExMap::Remove>: key 2424831 not found at 371
Warning in <TBufferFile::CheckObject>: reference to object of unavailable class TObject, offset=2424831 pointer will be 0
Error in <TRint::HandleTermInput()>: std::length_error caught: basic_string::_M_replace_aux
root [4]
```

</details>

Reading with uproot does not work either:

```python
import uproot
print(f"{uproot.__version__=}")

filename = "list.root"
key = "listOfStrings"

with uproot.open(filename) as f:
    print(f"keys: {f.keys()}")
    print(f"list: {f[key]}")
```

<details>
  <summary>error when reading with `uproot` the file generated using `uproot`:</summary>

```
uproot.__version__='5.0.0rc4'
keys: ['listOfStrings;1']
Traceback (most recent call last):
  File "/root/t.py", line 9, in <module>
    print(f"list: {f[key]}")
  File "/usr/local/lib/python3.10/dist-packages/uproot/reading.py", line 2107, in __getitem__
    return self.key(where).get()
  File "/usr/local/lib/python3.10/dist-packages/uproot/reading.py", line 2510, in get
    out = cls.read(chunk, cursor, context, self._file, selffile, parent)
  File "/usr/local/lib/python3.10/dist-packages/uproot/model.py", line 877, in read
    self.check_numbytes(chunk, cursor, context)
  File "/usr/local/lib/python3.10/dist-packages/uproot/model.py", line 952, in check_numbytes
    uproot.deserialization.numbytes_check(
  File "/usr/local/lib/python3.10/dist-packages/uproot/deserialization.py", line 167, in numbytes_check
    raise DeserializationError(
uproot.deserialization.DeserializationError: while reading

    TList version 5 as uproot.models.TList.Model_TList (176 bytes)
        (base): <TObject None None at 0x7f74785d4160>
        fName: ''
        fSize: 4
Base classes for TList: TObject?
Members for TList: fName?, fSize?

expected 176 bytes but cursor moved by -11251723 bytes (through TList)
in file list.root
in object /listOfStrings;1
```
</details>

**uproot works when reading the file written using root though**:

```python
import uproot
print(f"{uproot.__version__=}")

filename = "list.root"
key = "listOfStrings"

with uproot.open(filename) as f:
    print(f"keys: {f.keys()}")
    print(f"list: {f[key]}")
    print(f"list as json: {f[key].tojson()}")
    for i, s in enumerate(f[key]):
        print(f"string {i}: {s}")
```

```
uproot.__version__='5.0.0rc4'
keys: ['listOfStrings;1']
list: <TList of 4 items at 0x7f05c3c546a0>
list as json: {'_typename': 'TList', 'name': 'TList', 'arr': [{'_typename': 'TObjString', 'fUniqueID': 0, 'fBits': 50331648}, {'_typename': 'TObjString', 'fUniqueID': 0, 'fBits': 50331648}, {'_typename': 'TObjString', 'fUniqueID': 0, 'fBits': 50331648}, {'_typename': 'TObjString', 'fUniqueID': 0, 'fBits': 50331648}], 'opt': []}
string 0: this
string 1: is
string 2: a
string 3: test
```

I have tried writing a single `TObjString` into a root file and this works fine.

**Comment by lobis** [comment]
I think I might have found a fix for this, I will submit a PR later today.
