### ISSUE TITLE
Slicing a Dask RecordArray from Uproot raises a key error

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/uproot5#791]
I'm not 100% sure if this is a problem in Uproot or dask-awkward, but the error is at least coming from Uproot. The exact file I'm using is https://github.com/iris-hep/func_adl_uproot/blob/fb9cd8607739fce4c70c72ef395301effc3a2692/tests/scalars_tree_file.root, but I don't think this is file specific.

```python
>>> import uproot, dask_awkward as dak
>>> uproot.__version__
'5.0.0rc6'
>>> dak.__version__
'2022.12a1'
>>> da = uproot.dask('tests/scalars_tree_file.root:tree')
>>> da.layout
<RecordArray is_tuple='false' len='??'>
    <content index='0' field='int_branch'>
        <NumpyArray dtype='int32' len='??'>[?? ... ??]</NumpyArray>
    </content>
    <content index='1' field='long_branch'>
        <NumpyArray dtype='int64' len='??'>[?? ... ??]</NumpyArray>
    </content>
    <content index='2' field='float_branch'>
        <NumpyArray dtype='float32' len='??'>[?? ... ??]</NumpyArray>
    </content>
    <content index='3' field='double_branch'>
        <NumpyArray dtype='float64' len='??'>[?? ... ??]</NumpyArray>
    </content>
    <content index='4' field='bool_branch'>
        <NumpyArray dtype='bool' len='??'>[?? ... ??]</NumpyArray>
    </content>
</RecordArray>
>>> da[da.int_branch < 0].compute()
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 378, in free_symbols
    return list(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 90, in _walk_ast_yield_symbols
    yield from _walk_ast_yield_symbols(x, keys, aliases, functions, getter)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 94, in _walk_ast_yield_symbols
    yield from _walk_ast_yield_symbols(x, keys, aliases, functions, getter)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 90, in _walk_ast_yield_symbols
    yield from _walk_ast_yield_symbols(x, keys, aliases, functions, getter)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 90, in _walk_ast_yield_symbols
    yield from _walk_ast_yield_symbols(x, keys, aliases, functions, getter)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 73, in _walk_ast_yield_symbols
    raise KeyError(node.id)
KeyError: 'less'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/_dask.py", line 526, in __call__
    return self.hasbranches[i].arrays(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 919, in arrays
    arrays, expression_context, branchid_interpretation = _regularize_expressions(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 2986, in _regularize_expressions
    _regularize_expression(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 2854, in _regularize_expression
    for symbol in language.free_symbols(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 384, in free_symbols
    raise uproot.KeyInFileError(
uproot.exceptions.KeyInFileError: not found: 'less'
in file tests/scalars_tree_file.root
in object /tree;1
```

The non-dask version of this works as expected:

```python
>>> a = uproot.open('tests/scalars_tree_file.root:tree').arrays()
>>> a[a.int_branch < 0]
<Array [{int_branch: -1, ...}] type='1 * {int_branch: int32, long_branch: i...'>
```

It even works with dask-awkward if I start from the Awkward array itself, which maybe further suggests that the above problem is in Uproot:

```python
>>> da2 = dak.from_awkward(a, 1)
>>> da2[da2.int_branch < 0].compute()
<Array [{int_branch: -1, ...}] type='1 * {int_branch: int32, long_branch: i...'>
```

**Comment by masonproffitt** [comment]
This seems to have issues with other operations as well:

```python
>>> da[(da.int_branch > 0) & (da.int_branch < 1)].compute()
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 379, in free_symbols
    return list(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 91, in _walk_ast_yield_symbols
    yield from _walk_ast_yield_symbols(x, keys, aliases, functions, getter)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 95, in _walk_ast_yield_symbols
    yield from _walk_ast_yield_symbols(x, keys, aliases, functions, getter)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 91, in _walk_ast_yield_symbols
    yield from _walk_ast_yield_symbols(x, keys, aliases, functions, getter)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 91, in _walk_ast_yield_symbols
    yield from _walk_ast_yield_symbols(x, keys, aliases, functions, getter)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 74, in _walk_ast_yield_symbols
    raise KeyError(node.id)
KeyError: 'bitwise_and'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/_dask.py", line 592, in __call__
    return self.ttrees[i].arrays(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 808, in arrays
    arrays, expression_context, branchid_interpretation = _regularize_expressions(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 2921, in _regularize_expressions
    _regularize_expression(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 2789, in _regularize_expression
    for symbol in language.free_symbols(
  File "/home/user/miniconda3/envs/func_adl_uproot_rc/lib/python3.10/site-packages/uproot/language/python.py", line 385, in free_symbols
    raise uproot.KeyInFileError(
uproot.exceptions.KeyInFileError: not found: 'bitwise_and'
in file tests/scalars_tree_file.root
in object /tree;1
```
