### ISSUE TITLE
DAOD_PHYSLITE works in pure python interpretation, not in awkward-forth (uproot 5.0.0)

### ISSUE THREAD

**Issue by lgray** [scikit-hep/uproot5#798]
A test in coffea results in:
```
ValueError: 'skip beyond' in AwkwardForth runtime: tried to skip beyond the bounds of an input (0 or length)
```
when awkward forth is used, and passes when forcing the pure-python interpretation paths to be used.
These tests involve iterating over arrays and fully validating the data contained, so the arrays produced within the test are correct (and in fact the same data-wise as uproot4/awkward1).

To reproduce this:
```
$ pip install 'git+https://github.com/CoffeaTeam/coffea.git@awkward2_dev'
$ python -c 'from coffea.nanoevents import NanoEventsFactory, PHYSLITESchema; NanoEventsFactory.from_root("https://github.com/CoffeaTeam/coffea/blob/master/tests/samples/DAOD_PHYSLITE_21.2.108.0.art.pool.root?raw=true", treepath="CollectionTree", schemaclass=PHYSLITESchema, use_ak_forth=False).events()'
$ python -c 'from coffea.nanoevents import NanoEventsFactory, PHYSLITESchema; NanoEventsFactory.from_root("https://github.com/CoffeaTeam/coffea/blob/master/tests/samples/DAOD_PHYSLITE_21.2.108.0.art.pool.root?raw=true", treepath="CollectionTree", schemaclass=PHYSLITESchema, use_ak_forth=True).events()'
```

**Comment by jpivarski** [comment]
The file has been added to [scikit-hep-testdata 0.4.24](https://pypi.org/project/scikit-hep-testdata/) as "`uproot-issue-798.root`".

There are four branches that can be read by Uproot v4/pure Python and cannot be read by Uproot v5/AwkwardForth, and they represent two different types (probably just one error).

```python
>>> import uproot, skhep_testdata
>>> uproot.__version__
'5.0.0'
>>> tree = uproot.open(skhep_testdata.data_path("uproot-issue-798.root"))["CollectionTree"]
```

**AnalysisJetsAuxDyn.GhostTrack:** `std::vector<std::vector<ElementLink<DataVector<xAOD::IParticle>>`

```python
>>> tree["AnalysisJetsAuxDyn.GhostTrack"].interpretation
AsObjects(AsVector(True, AsVector(False, Model_ElementLink_3c_DataVector_3c_xAOD_3a3a_IParticle_3e3e_)))
>>> tree["AnalysisJetsAuxDyn.GhostTrack"].array()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 1818, in array
    _ranges_or_baskets_to_arrays(
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 3124, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/home/jpivarski/irishep/uproot5/src/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 3066, in basket_to_array
    basket_arrays[basket.basket_num] = interpretation.basket_array(
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 139, in basket_array
    output = self.basket_array_forth(
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 254, in basket_array_forth
    context["forth"].vm.resume()
ValueError: 'skip beyond' in AwkwardForth runtime: tried to skip beyond the bounds of an input (0 or length)
```

**TruthBosonAuxDyn.childLinks:** `std::vector<std::vector<ElementLink<DataVector<xAOD::TruthParticle_v1>>`

```python
>>> tree["TruthBosonAuxDyn.childLinks"].interpretation
AsObjects(AsVector(True, AsVector(False, Model_ElementLink_3c_DataVector_3c_xAOD_3a3a_TruthParticle_5f_v1_3e3e_)))
>>> tree["TruthBosonAuxDyn.childLinks"].array()
Traceback (most recent call last):
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 232, in basket_array_forth
    context["forth"].vm = awkward.forth.ForthMachine64(
ValueError: in AwkwardForth source code, line 6 col 1, input names, output names, variable names, and user-defined words must all be unique and not reserved words or integers:

    output node1-offsets 

(https://github.com/scikit-hep/awkward-1.0/blob//src/libawkward/forth/ForthMachine.cpp#L1960)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 1818, in array
    _ranges_or_baskets_to_arrays(
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 3124, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/home/jpivarski/irishep/uproot5/src/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 3066, in basket_to_array
    basket_arrays[basket.basket_num] = interpretation.basket_array(
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 139, in basket_array
    output = self.basket_array_forth(
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 236, in basket_array_forth
    raise type(err)(
ValueError: in AwkwardForth source code, line 6 col 1, input names, output names, variable names, and user-defined words must all be unique and not reserved words or integers:

    output node1-offsets 

(https://github.com/scikit-hep/awkward-1.0/blob//src/libawkward/forth/ForthMachine.cpp#L1960)

Forth code generated for this data type:

input stream
    input byteoffsets
    input bytestops
    output node0-offsets int64
output node1-offsets int64
output node1-offsets int64
output node10-data uint32
output node11-data uint32

    0 node0-offsets <- stack
0 node1-offsets <- stack
0 node1-offsets <- stack

    0 do
    byteoffsets I-> stack
    stream seek
    6 stream skip
stream !I-> stack
 dup node0-offsets +<- stack
0 do
stream !I-> stack
 dup node1-offsets +<- stack
0 do
stream !I-> stack
 dup node1-offsets +<- stack
0 do
0 stream skip 
6 stream skip
4 stream skip
stream !I-> node10-data
stream !I-> node11-data
loop
loop
loop

    loop
```

**TruthPhotonsAuxDyn.parentLinks:** `std::vector<std::vector<ElementLink<DataVector<xAOD::TruthParticle_v1>>`

```python
>>> tree["TruthPhotonsAuxDyn.parentLinks"].interpretation
AsObjects(AsVector(True, AsVector(False, Model_ElementLink_3c_DataVector_3c_xAOD_3a3a_TruthParticle_5f_v1_3e3e_)))
>>> tree["TruthPhotonsAuxDyn.parentLinks"].array()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 1818, in array
    _ranges_or_baskets_to_arrays(
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 3124, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/home/jpivarski/irishep/uproot5/src/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 3066, in basket_to_array
    basket_arrays[basket.basket_num] = interpretation.basket_array(
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 139, in basket_array
    output = self.basket_array_forth(
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 254, in basket_array_forth
    context["forth"].vm.resume()
ValueError: 'skip beyond' in AwkwardForth runtime: tried to skip beyond the bounds of an input (0 or length)
```

**TruthTopAuxDyn.parentLinks:** `std::vector<std::vector<ElementLink<DataVector<xAOD::TruthParticle_v1>>`

```python
>>> tree["TruthTopAuxDyn.parentLinks"].interpretation
AsObjects(AsVector(True, AsVector(False, Model_ElementLink_3c_DataVector_3c_xAOD_3a3a_TruthParticle_5f_v1_3e3e_)))
>>> tree["TruthTopAuxDyn.parentLinks"].array()
Traceback (most recent call last):
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 232, in basket_array_forth
    context["forth"].vm = awkward.forth.ForthMachine64(
ValueError: in AwkwardForth source code, line 6 col 1, input names, output names, variable names, and user-defined words must all be unique and not reserved words or integers:

    output node1-offsets 

(https://github.com/scikit-hep/awkward-1.0/blob//src/libawkward/forth/ForthMachine.cpp#L1960)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 1818, in array
    _ranges_or_baskets_to_arrays(
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 3124, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/home/jpivarski/irishep/uproot5/src/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/home/jpivarski/irishep/uproot5/src/uproot/behaviors/TBranch.py", line 3066, in basket_to_array
    basket_arrays[basket.basket_num] = interpretation.basket_array(
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 139, in basket_array
    output = self.basket_array_forth(
  File "/home/jpivarski/irishep/uproot5/src/uproot/interpretation/objects.py", line 236, in basket_array_forth
    raise type(err)(
ValueError: in AwkwardForth source code, line 6 col 1, input names, output names, variable names, and user-defined words must all be unique and not reserved words or integers:

    output node1-offsets 

(https://github.com/scikit-hep/awkward-1.0/blob//src/libawkward/forth/ForthMachine.cpp#L1960)

Forth code generated for this data type:

input stream
    input byteoffsets
    input bytestops
    output node0-offsets int64
output node1-offsets int64
output node1-offsets int64
output node158-data uint32
output node159-data uint32

    0 node0-offsets <- stack
0 node1-offsets <- stack
0 node1-offsets <- stack

    0 do
    byteoffsets I-> stack
    stream seek
    6 stream skip
stream !I-> stack
 dup node0-offsets +<- stack
0 do
stream !I-> stack
 dup node1-offsets +<- stack
0 do
stream !I-> stack
 dup node1-offsets +<- stack
0 do
0 stream skip 
6 stream skip
4 stream skip
stream !I-> node158-data
stream !I-> node159-data
loop
loop
loop

    loop
```

All four of them can be read without AwkwardForth (old method). I also verified that they can be read by Uproot v4 itself, and that there aren't any other branches that can be read in v4 but not v5.

```python
>>> interpretation = tree["AnalysisJetsAuxDyn.GhostTrack"].interpretation
>>> interpretation._forth = False
>>> tree["AnalysisJetsAuxDyn.GhostTrack"].array(interpretation)
<Array [[[{...}, {...}, ..., {...}], ...], ...] type='40 * var * var * stru...'>

>>> interpretation = tree["TruthBosonAuxDyn.childLinks"].interpretation
>>> interpretation._forth = False
>>> tree["TruthBosonAuxDyn.childLinks"].array(interpretation)
<Array [[[], [{...}, ..., {...}]], ..., [...]] type='40 * var * var * struc...'>

>>> interpretation = tree["TruthPhotonsAuxDyn.parentLinks"].interpretation
>>> interpretation._forth = False
>>> tree["TruthPhotonsAuxDyn.parentLinks"].array(interpretation)
<Array [[[{m_persKey: ..., ...}], ...], ...] type='40 * var * var * struct[...'>

>>> interpretation = tree["TruthTopAuxDyn.parentLinks"].interpretation
>>> interpretation._forth = False
>>> tree["TruthTopAuxDyn.parentLinks"].array(interpretation)
<Array [[[], [], [{...}], [{...}]], ..., [...]] type='40 * var * var * stru...'>
```

**Comment by nikoladze** [comment]
thanks for investigating this! Since i had some manual implementations for awkward-forth for exactly these branches i tried to compare the generated code with what i had. There are a couple of issues:

For `TruthBosonAuxDyn.childLinks` and also `TruthTopAuxDyn.parentLinks` the Forth Machine isn't even created since it tries to define `output node1-offsets` twice - which also seems to be described in the error message "... user-defined words must all be unique ..."

For the other two branches it seems to fail only later when running the machine. Here i could identify 2 issues - which i'll comment in the following generated code (i got this by printing `context["forth"].vm.decompiled` in pdb):

```
input stream
input byteoffsets
input bytestops
output node0-offsets int64
output node1-offsets int64
output node6-data uint32
output node7-data uint32

0
node0-offsets <- stack
0
node1-offsets <- stack
// there is a stop missing here - one could do `byteoffsets len 4 /`
0 
do
  byteoffsets I-> stack
  stream seek
  6
  stream skip
  stream !I-> stack
  dup
  node0-offsets +<- stack
  0
  do
    stream !I-> stack
    dup
    node1-offsets +<- stack
    0
    do
      // in the following block it skips 6 + 4 bytes, but it should skip 20 bytes (seems the header of these objects is that large)
      0
      stream skip
      0
      stream skip
      6
      stream skip
      4
      stream skip
      stream !I-> node6-data
      stream !I-> node7-data
    loop
  loop
loop
```

Running it with these fixes it can deserialize all 4 branches. In fact, i expect this to work for all `vector<vector<ElementLink<something>>` :

```pycon
>>> import numpy as np
>>> import uproot, skhep_testdata
>>> uproot.__version__
'5.0.2'
>>> import awkward as ak
>>> ak.__version__
'2.0.6'
>>> fm_code = """
input stream
input byteoffsets
input bytestops
output node0-offsets int64
output node1-offsets int64
output node6-data uint32
output node7-data uint32

0
node0-offsets <- stack
0
node1-offsets <- stack
byteoffsets len 4 /
0
do
  byteoffsets I-> stack
  stream seek
  6
  stream skip
  stream !I-> stack
  dup
  node0-offsets +<- stack
  0
  do
    stream !I-> stack
    dup
    node1-offsets +<- stack
    0
    do
      20
      stream skip
      stream !I-> node6-data
      stream !I-> node7-data
    loop
  loop
loop
"""
>>> tree = uproot.open(skhep_testdata.data_path("uproot-issue-798.root"))["CollectionTree"]
>>> basket = tree["TruthBosonAuxDyn.childLinks"].basket(0)
>>> inputs = {
    "stream": basket.data,
    "byteoffsets": basket.byte_offsets[:-1],
    "bytestops": basket.byte_offsets[1:]
}
>>> machine = ak.forth.ForthMachine32(fm_code)
>>> machine.run(inputs)
```
The outputs of this seem to match what the non-forth version spits out
```python
interpretation = tree["TruthBosonAuxDyn.childLinks"].interpretation
interpretation._forth = False
array = tree["TruthBosonAuxDyn.childLinks"].array(interpretation)
assert ak.all(array.layout.offsets == machine.outputs["node0-offsets"])
assert ak.all(array.layout.content.offsets == machine.outputs["node1-offsets"])
assert ak.all(np.asarray(array.layout.content.content.content(0)) == machine.outputs["node6-data"])
assert ak.all(np.asarray(array.layout.content.content.content(1)) == machine.outputs["node7-data"])
```
