### ISSUE TITLE
uproot fails to read branch of TVector3 created with RDF::Snapshot

### ISSUE THREAD

**Issue by davehadley** [scikit-hep/uproot5#814]
The following example script generates two files with the same data in slightly different ways. `uproot` can successfully read the first file. But it fails to read the second file (created with `RDF::Snapshot`).
```python
import ROOT
import uproot

def make_file_1_with_root():
    tfile = ROOT.TFile("tfile_with_tvector3_1.root", "RECREATE")
    tree = ROOT.TTree("tree", "tree")
    tvector3 = ROOT.TVector3()
    tree.Branch("tvector3", tvector3)
    for x in range(10):
        tvector3.SetX(x)
        tree.Fill()
    tree.AutoSave()
    tfile.Close()

def make_file_2_with_root():
    tfile = ROOT.TFile("tfile_with_tvector3_1.root", "READ")
    tree = tfile.Get("tree")
    rdf = ROOT.RDataFrame(tree)
    branchlist = ROOT.std.vector(ROOT.std.string)()
    branchlist.push_back("tvector3")
    rdf.Snapshot("tree", "tfile_with_tvector3_2.root", branchlist)
    return

def read_file_1_with_uproot():
    print("reading file 1")
    uproot.open("tfile_with_tvector3_1.root:tree").arrays()

def read_file_2_with_uproot():
    print("reading file 2")
    uproot.open("tfile_with_tvector3_2.root:tree").arrays()


make_file_1_with_root()
make_file_2_with_root()
read_file_1_with_uproot() # uproot successfully reads file 1
read_file_2_with_uproot() # uproot fails to read file 2
```

`uproot.open("tfile_with_tvector3_2.root:tree").arrays()` fails with the error message:

```
Traceback (most recent call last):
  File "/home/dave/work/reproduce_uproot_bug/reproduce_uproot_bug.py", line 36, in <module>
    read_file_2_with_uproot() # uproot fails to read file 2
  File "/home/dave/work/reproduce_uproot_bug/reproduce_uproot_bug.py", line 30, in read_file_2_with_uproot
    uproot.open("tfile_with_tvector3_2.root:tree").arrays()
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 834, in arrays
    _ranges_or_baskets_to_arrays(
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 3124, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 3093, in basket_to_array
    arrays[branch.cache_key] = interpretation.final_array(
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/uproot/interpretation/objects.py", line 397, in final_array
    output = library.finalize(
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/uproot/interpretation/library.py", line 592, in finalize
    unlabeled = awkward.from_iter(
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/awkward/operations/ak_from_iter.py", line 69, in from_iter
    return _impl(iterable, highlevel, behavior, allow_record, initial, resize)
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/awkward/operations/ak_from_iter.py", line 94, in _impl
    builder.fromiter(iterable)
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/uproot/interpretation/library.py", line 593, in <genexpr>
    (_object_to_awkward_json(form, x) for x in array), highlevel=False
  File "/home/dave/work/reproduce_uproot_bug/env/uprootbug/lib/python3.10/site-packages/uproot/interpretation/library.py", line 323, in _object_to_awkward_json
    return [_object_to_awkward_json(subform, x) for x in obj]
TypeError: 'Model_TVector3_v3' object is not iterable

```

ROOT seems to be able to read the second file fine without problems so I don't think it's a bug in `RDF::Snapshot` causing a corrupt file.

Versions:
```
python==3.10
root==6.26.10
uproot==5.0.2
```

A small project that reproduces the issue:
[reproduce_uproot_bug.zip](https://github.com/scikit-hep/uproot5/files/10383299/reproduce_uproot_bug.zip)

The two files:
[tfiles_with_tvector3.zip](https://github.com/scikit-hep/uproot5/files/10383314/tfiles_with_tvector3.zip)

**Comment by davehadley** [comment]
I have tested the minor ROOT versions available on `conda-forge` (`6.20.6`, `6.22.8`, `6.24.6`, `6.26.10`). The example above works with the following versions:
```
python==3.8
root==6.20.10
uproot==5.0.2
```

If you are hit by this problem, and downgrading your ROOT is an option, this is a possible work around.
