### ISSUE TITLE
Not reading / opening of root file from uproot

### ISSUE THREAD

**Issue by newsid2024** [scikit-hep/uproot5#858]
I am trying to read a file.root using **uproot** but it's throwing back this error :-

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/siddharthkeshar/opt/anaconda3/lib/python3.9/site-packages/uproot/reading.py", line 152, in open
    return file.root_directory
  File "/Users/siddharthkeshar/opt/anaconda3/lib/python3.9/site-packages/uproot/reading.py", line 785, in root_directory
    return ReadOnlyDirectory(
  File "/Users/siddharthkeshar/opt/anaconda3/lib/python3.9/site-packages/uproot/reading.py", line 1426, in __init__
    ReadOnlyKey(keys_chunk, keys_cursor, {}, file, self, read_strings=True)
  File "/Users/siddharthkeshar/opt/anaconda3/lib/python3.9/site-packages/uproot/reading.py", line 2266, in __init__
    ) = cursor.fields(chunk, _key_format_small, context, move=False)
  File "/Users/siddharthkeshar/opt/anaconda3/lib/python3.9/site-packages/uproot/source/cursor.py", line 194, in fields
    return format.unpack(chunk.get(start, stop, self, context))
  File "/Users/siddharthkeshar/opt/anaconda3/lib/python3.9/site-packages/uproot/source/chunk.py", line 417, in get
    self.wait(insist=stop)
  File "/Users/siddharthkeshar/opt/anaconda3/lib/python3.9/site-packages/uproot/source/chunk.py", line 370, in wait
    raise OSError(
[file.txt](https://github.com/scikit-hep/uproot5/files/10974931/file.txt)

OSError: expected Chunk of length 395,
received 0 bytes from MemmapSource
for file path /Users/siddharthkeshar/Desktop/file.root
```

How can i resolve this error ?

I am using uproot version : 5.0.4

```python
>>> import uproot
>>> file = uproot.open("/Users/siddharthkeshar/Desktop/file.root")
```

**Comment by jpivarski** [comment]
It seems to be the file itself that's at fault. As a first step, I tried to open it in ROOT:

```python
>>> import ROOT
>>> f = ROOT.TFile("uproot-issue-858.root")
```

```
Error in <TFile::Init>: file uproot-issue-858.root is truncated at 25736752 bytes: should be 2186062826, trying to recover
TFile::Init:0: RuntimeWarning: no keys recovered, file has been made a Zombie
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/mambaforge/lib/python3.9/site-packages/ROOT/_pythonization/_tfile.py", line 55, in _TFileConstructor
    raise OSError('Failed to open file {}'.format(args[0]))
OSError: Failed to open file uproot-issue-858.root
```

From the stack trace that you provided above, it looks like the TFile header is intact, as is the first half of the root TDirectory, but not its second half.

The `fEND` field of the TFile header, which says how large ROOT thinks the file is, says that the file is 2186062826 bytes (2084 MB), but the actual size of the file is 25736752 bytes (24 MB).

I think you just got the first 1.1% of a much larger file, and I think it got this way by being chopped off. Maybe it was a download that failed early, leaving you with only the very beginning of the file. Just enough to be confusing!

I'm going to close this because it's not indicative of an Uproot bug. If you get the whole file and it still doesn't work, go ahead and open a new issue (because it would be a _different_ issue).
