### ISSUE TITLE
Exception on accessing `.interpretation` member for some non-numeric branches

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/uproot5#906]
For some branches i get an Exception when `.interpretation` is accessed. Noticed this when working on the coffea PHYSLITE interpretation (the NanoEvents factory tries to check whether a branch is readable in uproot by looking at the interpretation). It also happens when i call `tree.show()`.

```python
>>> import uproot
>>> uproot.__version__
'5.0.8'
```

Example:

```python
from skhep_testdata import data_path
import uproot
filename = data_path("uproot-issue-798.root") # PHYSLITE example file
f = uproot.open(filename)
tree = f["CollectionTree"]

>>> tree["EventInfo"].interpretation
Traceback (most recent call last):
  File "/home/nikolai/python/uproot4/src/uproot/interpretation/identify.py", line 383, in interpretation_of
    from_dtype = _leaf_to_dtype(leaf, getdims=False).newbyteorder(">")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/python/uproot4/src/uproot/interpretation/identify.py", line 102, in _leaf_to_dtype
    return numpy.dtype((_ftype_to_dtype(leaf.member("fType")), dims))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/python/uproot4/src/uproot/interpretation/identify.py", line 60, in _ftype_to_dtype
    raise NotNumerical()
uproot.interpretation.identify.NotNumerical

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikolai/python/uproot4/src/uproot/behaviors/TBranch.py", line 1933, in interpretation
    self._interpretation = uproot.interpretation.identify.interpretation_of(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/python/uproot4/src/uproot/interpretation/identify.py", line 460, in interpretation_of
    return out.simplify()
           ^^^^^^^^^^^^^^
  File "/home/nikolai/python/uproot4/src/uproot/interpretation/objects.py", line 450, in simplify
    return self._model.strided_interpretation(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/python/uproot4/src/uproot/model.py", line 1210, in strided_interpretation
    return versioned_cls.strided_interpretation(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<dynamic>", line 48, in strided_interpretation
  File "<dynamic>", line 48, in strided_interpretation
  File "<dynamic>", line 30, in strided_interpretation
  File "/home/nikolai/python/uproot4/src/uproot/interpretation/objects.py", line 600, in __init__
    while members[first_value_loc] == (None, None):
          ~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

This happens for a lot of branches that don't contain any numerical data and that we anyway want to skip, but i think it should not raise an Exception when accessing `.interpretation`.

**Comment by jpivarski** [comment]
This is another high-priority item, like the one I mentioned in https://github.com/scikit-hep/uproot5/issues/908#issuecomment-1608423979. (And, similarly, it has been staring at me in my email inbox while I've been thinking about how to devote some time to it.)
